import { describe, expect, it } from "vitest";
import {
  saveGeneratedProject,
  saveProjectNarration,
  saveProjectPlan,
  saveProjectVisuals,
  saveProjectVideos,
  loadProject,
  type ProjectsClient,
  type ProjectRow,
  type NewProjectRow,
  type ProjectUpdatePatch,
  type ProjectAssetsClient,
  type NewVisualAssetRow,
  type NewVideoAssetRow,
} from "@/lib/actions/project-persistence";
import type { ResolvedSceneVisual } from "@/lib/visuals/types";
import type { ResolvedSceneVideo } from "@/lib/video-generation/types";
import type { PlanNarrationResult } from "@/lib/audio/plan-narration";
import type { NarrationStorageClient } from "@/lib/audio/narration-storage";
import type { VideoPlan } from "@/lib/ai/video-plan-schema";
import type { Json } from "@/lib/supabase/database.types";
import type { EntitlementClient, EntitlementStatus, ConsumeTrialResult } from "@/lib/supabase/usage";

/**
 * project-persistence.ts takes injected ProjectsClient/NarrationStorageClient
 * interfaces rather than a real Supabase client — the same pattern
 * lib/audio/plan-narration.ts and lib/audio/narration-storage.ts already
 * use — specifically so these tests never touch "server-only" or make a
 * real network/paid API call. lib/actions/project-actions.ts wires the real
 * (authenticated, RLS-scoped, never service-role) Supabase adapter in for
 * production.
 */

function makePlan(overrides: Partial<VideoPlan> & { scenes: VideoPlan["scenes"] }): VideoPlan {
  return {
    language: "ar",
    videoTitle: "Acme Ad",
    business: "Acme Co",
    objective: "Sell burgers",
    targetAudience: "Young adults",
    platform: "reels",
    aspectRatio: "9:16",
    durationSeconds: 15,
    visualStyle: "fast",
    tone: "energetic",
    brandColors: null,
    palette: null,
    visualTheme: null,
    cta: "Order now",
    audio: null,
    ...overrides,
  };
}

function scene(id: string, narration: string | null): VideoPlan["scenes"][number] {
  return {
    id,
    startTime: 0,
    duration: 5,
    purpose: "hook",
    narration,
    onScreenText: "Hello",
    visualDirection: "product on table",
    motionDirection: "slow zoom",
    transition: "cut",
    assetNeeds: [],
    textPosition: "center",
    textAlign: "center",
    visual: null,
  };
}

/** videoPlanSchema requires at least MIN_SCENES (3) scenes — these two silent filler scenes pad any test plan up to that minimum without adding narration to synthesize. */
const FILLER_SCENES = [scene("filler-1", null), scene("filler-2", null)];

/** In-memory fake — a real row store keyed by id, scoped by owner exactly like the real Supabase adapter (RLS + explicit .eq("owner_id", ...)) is meant to be. Tracks `status` too (beyond what ProjectRow/loadProject need) purely so tests can assert on it. */
function makeFakeProjectsClient() {
  const rows = new Map<string, ProjectRow & { owner_id: string; status: string }>();
  let nextId = 1;

  const client: ProjectsClient = {
    async insertProject(row: NewProjectRow) {
      const id = `project-${nextId++}`;
      rows.set(id, { id, prompt: row.prompt, scene_plan: row.scene_plan, narration: null, owner_id: row.owner_id, status: row.status });
      return { ok: true, id };
    },
    async updateProject(projectId: string, ownerId: string, patch: ProjectUpdatePatch) {
      const existing = rows.get(projectId);
      if (!existing || existing.owner_id !== ownerId) return { ok: false, error: "not found or not owned" };
      rows.set(projectId, { ...existing, ...patch });
      return { ok: true };
    },
    async selectProject(projectId: string, ownerId: string) {
      const existing = rows.get(projectId);
      if (!existing || existing.owner_id !== ownerId) return null;
      const { owner_id: _owner_id, ...row } = existing;
      return row;
    },
  };

  return { client, rows };
}

/** In-memory fake ProjectAssetsClient — a real row store scoped by (project, owner), mirroring makeFakeProjectsClient's shape. Holds both auto-generated-visual and AI-video rows, exactly like the real project_assets table does. */
function makeFakeProjectAssetsClient() {
  const visualRows: (NewVisualAssetRow & { id: string })[] = [];
  const videoRows: (NewVideoAssetRow & { id: string })[] = [];
  let nextId = 1;
  const client: ProjectAssetsClient = {
    async insertVisualAsset(row) {
      visualRows.push({ ...row, id: `asset-${nextId++}` });
      return { ok: true };
    },
    async listAutoGeneratedVisuals(projectId, ownerId) {
      return visualRows
        .filter((r) => r.project_id === projectId && r.owner_id === ownerId && r.kind === "auto-generated")
        .map((r) => ({ scene_id: r.scene_id, storage_path: r.storage_path, provider: r.metadata.provider, prompt: r.metadata.prompt, estimated_usd: r.metadata.estimatedUsd }));
    },
    async insertVideoAsset(row) {
      videoRows.push({ ...row, id: `asset-${nextId++}` });
      return { ok: true };
    },
    async listAiVideos(projectId, ownerId) {
      return videoRows
        .filter((r) => r.project_id === projectId && r.owner_id === ownerId && r.kind === "ai-video")
        .map((r) => ({
          scene_id: r.scene_id,
          storage_path: r.storage_path,
          provider: r.metadata.provider,
          model: r.metadata.model,
          provider_task_id: r.metadata.providerTaskId,
          duration_seconds: r.metadata.durationSeconds,
          motion_prompt: r.metadata.motionPrompt,
          provider_cost: r.metadata.providerCost,
        }));
    },
  };
  return { client, rows: visualRows, videoRows };
}

function fakeStorage(): NarrationStorageClient {
  return {
    from: () => ({
      upload: async () => ({ error: null }),
      createSignedUrl: async (path: string) => ({ data: { signedUrl: `https://storage.example/fresh-signed/${path}` }, error: null }),
    }),
  };
}

function narrationResult(sceneAudio: PlanNarrationResult["sceneAudio"]): PlanNarrationResult {
  const narrationAudioUrls: Record<string, string> = {};
  for (const [id, audio] of Object.entries(sceneAudio)) if (audio.audioUrl) narrationAudioUrls[id] = audio.audioUrl;
  return { narrationAudioUrls, sceneAudio, status: "ok", cost: { characters: 100, estimatedUsd: 0.01 } };
}

/** In-memory fake — defaults to "always entitled, trial available, no subscription" (the common case for tests that aren't about entitlement itself). Tracks every consumeTrial call for tests that need to assert on it. */
function makeFakeEntitlementClient(
  overrides: Partial<{ status: EntitlementStatus; consumeTrial: EntitlementClient["consumeTrial"] }> = {},
) {
  const consumeTrialCalls: { userId: string; projectId: string }[] = [];
  const status: EntitlementStatus = overrides.status ?? {
    trialAvailable: true,
    trialConsumed: false,
    activeSubscription: false,
    expiredSubscription: false,
    canGenerate: true,
  };

  const client: EntitlementClient = {
    getStatus: async () => status,
    consumeTrial:
      overrides.consumeTrial ??
      (async (userId, projectId): Promise<ConsumeTrialResult> => {
        consumeTrialCalls.push({ userId, projectId });
        return { ok: true, status: "consumed" };
      }),
  };

  return { client, consumeTrialCalls };
}

/** Shared default for every test below that isn't specifically testing entitlement behavior. */
const ALWAYS_ALLOWED_ENTITLEMENT = makeFakeEntitlementClient().client;

const OWNER_A = "user-aaaa";
const OWNER_B = "user-bbbb";

describe("saveGeneratedProject", () => {
  it("(create/save project) inserts owner_id, prompt, and the full VideoPlan JSON", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });

    const result = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "make me an ad", plan);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const row = rows.get(result.projectId);
    expect(row?.owner_id).toBe(OWNER_A);
    expect(row?.prompt).toBe("make me an ad");
    expect(row?.scene_plan).toEqual(plan);
  });

  describe("entitlement enforcement (locked business rule: one free trial, then an active subscription)", () => {
    it("(brand-new user has exactly one trial) a user whose trial is available and unconsumed is allowed to generate", async () => {
      const { client } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient({
        status: { trialAvailable: true, trialConsumed: false, activeSubscription: false, expiredSubscription: false, canGenerate: true },
      });
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      const result = await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(result.ok).toBe(true);
    });

    it("(first successful generation consumes it once) calls consumeTrial exactly once, tied to the new project id", async () => {
      const { client } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient();
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      const result = await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(entitlement.consumeTrialCalls).toEqual([{ userId: OWNER_A, projectId: result.projectId }]);
    });

    it("(second new generation blocked without subscription) refuses to save when the trial is already consumed and there's no active subscription", async () => {
      const { client, rows } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient({
        status: { trialAvailable: false, trialConsumed: true, activeSubscription: false, expiredSubscription: false, canGenerate: false },
      });
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      const result = await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(result).toEqual({ ok: false, error: expect.any(String), code: "entitlement_blocked" });
      expect(rows.size).toBe(0); // no orphaned project row created for a blocked request
      expect(entitlement.consumeTrialCalls).toEqual([]); // never even attempted
    });

    it("(active monthly/annual subscription allows generation) a subscribed user is allowed even with an already-consumed trial", async () => {
      const { client } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient({
        status: { trialAvailable: false, trialConsumed: true, activeSubscription: true, expiredSubscription: false, canGenerate: true },
      });
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      const result = await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(result.ok).toBe(true);
    });

    it("a subscribed user's generation never consumes the trial, even if it's still available", async () => {
      const { client } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient({
        status: { trialAvailable: true, trialConsumed: false, activeSubscription: true, expiredSubscription: false, canGenerate: true },
      });
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(entitlement.consumeTrialCalls).toEqual([]);
    });

    it("(expired subscription blocks generation) a user with only an expired subscription and a consumed trial is blocked", async () => {
      const { client, rows } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient({
        status: { trialAvailable: false, trialConsumed: true, activeSubscription: false, expiredSubscription: true, canGenerate: false },
      });
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      const result = await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(result.ok).toBe(false);
      expect(rows.size).toBe(0);
    });

    it("(failure safety) a transient consumeTrial failure never loses the already-saved project", async () => {
      const { client, rows } = makeFakeProjectsClient();
      const entitlement = makeFakeEntitlementClient({ consumeTrial: async () => ({ ok: false, error: "temporary RPC failure" }) });
      const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });

      const result = await saveGeneratedProject(client, entitlement.client, OWNER_A, "brief", plan);

      expect(result.ok).toBe(true);
      if (result.ok) expect(rows.has(result.projectId)).toBe(true);
    });
  });
});

describe("loadProject", () => {
  it("(loading own project + VideoPlan persistence) round-trips the exact VideoPlan that was saved", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.plan).toEqual(plan);
    expect(result.prompt).toBe("brief");
  });

  it("(rejecting another user's project) returns not_found for a project owned by someone else", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_B, saved.projectId);

    expect(result).toEqual({ ok: false, code: "not_found" });
  });

  it("returns not_found for a project id that was never created", async () => {
    const { client } = makeFakeProjectsClient();
    const result = await loadProject(client, fakeStorage(), OWNER_A, "does-not-exist");
    expect(result).toEqual({ ok: false, code: "not_found" });
  });

  it("returns invalid for a stored scene_plan that no longer matches the schema", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const inserted = await client.insertProject({
      owner_id: OWNER_A,
      prompt: "x",
      language: "ar",
      style: "fast",
      platform: "reels",
      aspect_ratio: "9:16",
      duration_seconds: 10,
      status: "generating",
      scene_plan: { not: "a valid plan" } as unknown as Json,
    });
    if (!inserted.ok) throw new Error("setup failed");
    void rows;

    const result = await loadProject(client, fakeStorage(), OWNER_A, inserted.id);
    expect(result).toEqual({ ok: false, code: "invalid" });
  });

  it("(backward compatibility) still loads a legacy project whose stored scene_plan predates the `palette` field entirely", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });
    const { palette: _palette, ...legacyPlanWithoutPaletteKey } = plan;
    const inserted = await client.insertProject({
      owner_id: OWNER_A,
      prompt: "brief",
      language: plan.language,
      style: plan.visualStyle,
      platform: plan.platform,
      aspect_ratio: plan.aspectRatio,
      duration_seconds: plan.durationSeconds,
      status: "generating",
      scene_plan: legacyPlanWithoutPaletteKey as unknown as Json,
    });
    if (!inserted.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_A, inserted.id);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.plan.palette).toBeNull();
  });

  it("(backward compatibility) still loads a legacy project whose stored scene_plan predates `visualTheme` and every scene's `visual` field entirely", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });
    const { visualTheme: _visualTheme, ...rest } = plan;
    const legacyPlanWithoutVisualKeys = {
      ...rest,
      scenes: rest.scenes.map((s) => {
        const { visual: _visual, ...sceneRest } = s;
        return sceneRest;
      }),
    };
    const inserted = await client.insertProject({
      owner_id: OWNER_A,
      prompt: "brief",
      language: plan.language,
      style: plan.visualStyle,
      platform: plan.platform,
      aspect_ratio: plan.aspectRatio,
      duration_seconds: plan.durationSeconds,
      status: "generating",
      scene_plan: legacyPlanWithoutVisualKeys as unknown as Json,
    });
    if (!inserted.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_A, inserted.id);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.plan.visualTheme).toBeNull();
    expect(result.plan.scenes.every((s) => s.visual === null)).toBe(true);
  });

  it("(fresh signed URL generation on reload) reissues a signed URL from the stored storagePath, never reusing an old one", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const original = narrationResult({
      s1: { audioUrl: "https://storage.example/OLD-EXPIRED-SIGNED-URL", storagePath: "u/g/s1.mp3", contentType: "audio/mpeg", durationSeconds: 3, provider: "elevenlabs", characters: 30, estimatedUsd: 0.003 },
    });
    await saveProjectNarration(client, OWNER_A, saved.projectId, plan, original);

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.narration.narrationAudioUrls.s1).toBe("https://storage.example/fresh-signed/u/g/s1.mp3");
    expect(result.narration.narrationAudioUrls.s1).not.toBe("https://storage.example/OLD-EXPIRED-SIGNED-URL");
  });

  it("leaves a scene with no storagePath as audioUrl: null, without attempting to sign it", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "narration one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const original = narrationResult({
      s1: { audioUrl: null, storagePath: null, contentType: null, durationSeconds: 3, provider: "silent-fallback", characters: 30, estimatedUsd: null },
    });
    await saveProjectNarration(client, OWNER_A, saved.projectId, plan, original);

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.narration.sceneAudio.s1.audioUrl).toBeNull();
    expect(result.narration.status).toBe("failed");
  });

  it("derives status ok/partial from the stored narration exactly like a fresh generation would", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), scene("s2", "two"), scene("s3", null)] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    await saveProjectNarration(
      client,
      OWNER_A,
      saved.projectId,
      plan,
      narrationResult({
        s1: { audioUrl: "https://x/s1", storagePath: "u/g/s1.mp3", contentType: "audio/mpeg", durationSeconds: 3, provider: "elevenlabs", characters: 10, estimatedUsd: 0.001 },
        s2: { audioUrl: null, storagePath: null, contentType: null, durationSeconds: 3, provider: "silent-fallback", characters: 10, estimatedUsd: null },
      }),
    );

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId);
    expect(result.ok).toBe(true);
    if (result.ok) expect(result.narration.status).toBe("partial");
  });
});

describe("saveProjectNarration", () => {
  it("(narration storage path persistence, no signed URL persisted) stores storagePath/provider/cost but never audioUrl", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    await saveProjectNarration(
      client,
      OWNER_A,
      saved.projectId,
      plan,
      narrationResult({
        s1: { audioUrl: "https://storage.example/signed/should-not-be-persisted", storagePath: "u/g/s1.mp3", contentType: "audio/mpeg", durationSeconds: 3, provider: "elevenlabs", characters: 42, estimatedUsd: 0.0042 },
      }),
    );

    const storedNarration = rows.get(saved.projectId)?.narration as Record<string, unknown>;
    expect(storedNarration.s1).toEqual({
      storagePath: "u/g/s1.mp3",
      contentType: "audio/mpeg",
      durationSeconds: 3,
      provider: "elevenlabs",
      characters: 42,
      estimatedUsd: 0.0042,
    });
    expect(JSON.stringify(storedNarration)).not.toContain("signed");
    expect(JSON.stringify(storedNarration)).not.toContain("should-not-be-persisted");
  });

  it("sets status to ready after narration concludes", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    await saveProjectNarration(client, OWNER_A, saved.projectId, plan, narrationResult({}));

    expect(rows.get(saved.projectId)?.status).toBe("ready");
  });

  it("(retry updates metadata/path correctly) a second call overwrites the first scene's stored metadata rather than merging or duplicating it", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    await saveProjectNarration(
      client,
      OWNER_A,
      saved.projectId,
      plan,
      narrationResult({
        s1: { audioUrl: "https://x/old", storagePath: "u/g/s1.mp3", contentType: "audio/mpeg", durationSeconds: 3, provider: "elevenlabs", characters: 10, estimatedUsd: 0.001 },
      }),
    );

    await saveProjectNarration(
      client,
      OWNER_A,
      saved.projectId,
      plan,
      narrationResult({
        s1: { audioUrl: "https://x/new", storagePath: "u/g/s1.mp3", contentType: "audio/mpeg", durationSeconds: 4, provider: "openai", characters: 12, estimatedUsd: 0.0002 },
      }),
    );

    const storedNarration = rows.get(saved.projectId)?.narration as Record<string, unknown>;
    expect(Object.keys(storedNarration)).toEqual(["s1"]);
    expect(storedNarration.s1).toMatchObject({ provider: "openai", durationSeconds: 4, characters: 12 });
  });

  it("(ownership) cannot update a project owned by a different user", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await saveProjectNarration(client, OWNER_B, saved.projectId, plan, narrationResult({}));

    expect(result.ok).toBe(false);
    expect(rows.get(saved.projectId)?.narration).toBeNull();
  });
});

describe("saveProjectPlan", () => {
  it("persists an edited VideoPlan without touching narration", async () => {
    const { client, rows } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "original narration"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const editedPlan = makePlan({ scenes: [scene("s1", "edited narration"), ...FILLER_SCENES] });
    const result = await saveProjectPlan(client, OWNER_A, saved.projectId, editedPlan);

    expect(result.ok).toBe(true);
    expect(rows.get(saved.projectId)?.scene_plan).toEqual(editedPlan);
  });

  it("(ownership) cannot edit a project owned by a different user", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await saveProjectPlan(client, OWNER_B, saved.projectId, plan);
    expect(result.ok).toBe(false);
  });
});

describe("saveProjectVisuals", () => {
  function autoVisual(sceneId: string, overrides: Partial<ResolvedSceneVisual> = {}): ResolvedSceneVisual {
    return { sceneId, url: `https://storage.example/signed/${sceneId}`, source: "auto-generated", storagePath: `u/gen/visuals/${sceneId}.png`, prompt: "a coffee cup", provider: "openai:gpt-image-1", estimatedUsd: 0.07, ...overrides };
  }

  it("persists one project_assets row per auto-generated scene visual", async () => {
    const { client: projectAssets, rows } = makeFakeProjectAssetsClient();

    await saveProjectVisuals(projectAssets, OWNER_A, "project-1", { s1: autoVisual("s1"), s2: autoVisual("s2") });

    expect(rows).toHaveLength(2);
    expect(rows[0]).toMatchObject({ project_id: "project-1", owner_id: OWNER_A, kind: "auto-generated", scene_id: "s1", storage_path: "u/gen/visuals/s1.png" });
  });

  it("never persists a row for a user-uploaded visual (only auto-generated ones need durable Storage bookkeeping here)", async () => {
    const { client: projectAssets, rows } = makeFakeProjectAssetsClient();

    await saveProjectVisuals(projectAssets, OWNER_A, "project-1", { s1: { sceneId: "s1", url: "blob:local", source: "user-product" } });

    expect(rows).toHaveLength(0);
  });

  it("continues persisting remaining visuals even when one insert fails", async () => {
    const rows: NewVisualAssetRow[] = [];
    const projectAssets: ProjectAssetsClient = {
      async insertVisualAsset(row) {
        if (row.scene_id === "s1") return { ok: false, error: "db error" };
        rows.push(row);
        return { ok: true };
      },
      async listAutoGeneratedVisuals() {
        return [];
      },
      async insertVideoAsset() {
        return { ok: true };
      },
      async listAiVideos() {
        return [];
      },
    };

    await saveProjectVisuals(projectAssets, OWNER_A, "project-1", { s1: autoVisual("s1"), s2: autoVisual("s2") });

    expect(rows).toHaveLength(1);
    expect(rows[0].scene_id).toBe("s2");
  });
});

describe("loadProject visuals", () => {
  it("re-signs and returns every persisted auto-generated visual, keyed by scene id", async () => {
    const { client } = makeFakeProjectsClient();
    const { client: projectAssets } = makeFakeProjectAssetsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    await saveProjectVisuals(projectAssets, OWNER_A, saved.projectId, {
      s1: { sceneId: "s1", url: "ignored-stale-url", source: "auto-generated", storagePath: "u/gen/visuals/s1.png", prompt: "a coffee cup", provider: "openai:gpt-image-1", estimatedUsd: 0.07 },
    });

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId, projectAssets);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.visuals.s1).toMatchObject({ sceneId: "s1", source: "auto-generated", storagePath: "u/gen/visuals/s1.png", provider: "openai:gpt-image-1" });
    expect(result.visuals.s1.url).toBe("https://storage.example/fresh-signed/u/gen/visuals/s1.png"); // freshly re-signed, never the stale persisted one
  });

  it("returns an empty visuals map when no ProjectAssetsClient is supplied (every existing caller keeps working unchanged)", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.visuals).toEqual({});
  });

  it("(Requirement 11: fallback) drops a visual whose Storage object can no longer be re-signed, without failing the whole load", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const projectAssets: ProjectAssetsClient = {
      async insertVisualAsset() {
        return { ok: true };
      },
      async listAutoGeneratedVisuals() {
        return [{ scene_id: "s1", storage_path: "gone.png", provider: "openai:gpt-image-1", prompt: "x", estimated_usd: 0.07 }];
      },
      async insertVideoAsset() {
        return { ok: true };
      },
      async listAiVideos() {
        return [];
      },
    };
    const brokenStorage: NarrationStorageClient = { from: () => ({ upload: async () => ({ error: null }), createSignedUrl: async () => ({ data: null, error: { message: "object not found" } }) }) };

    const result = await loadProject(client, brokenStorage, OWNER_A, saved.projectId, projectAssets);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.visuals).toEqual({});
  });
});

describe("saveProjectVideos", () => {
  function aiVideo(sceneId: string, overrides: Partial<ResolvedSceneVideo> = {}): ResolvedSceneVideo {
    return {
      sceneId,
      url: `https://storage.example/signed/${sceneId}.mp4`,
      source: "ai-generated",
      storagePath: `u/gen/videos/${sceneId}.mp4`,
      provider: "runway:gen4_turbo",
      model: "gen4_turbo",
      providerTaskId: "task-123",
      durationSeconds: 5,
      motionPrompt: "the liquid pours and steam rises",
      providerCost: 25,
      ...overrides,
    };
  }

  it("persists one project_assets row per AI-generated scene video", async () => {
    const { client: projectAssets, videoRows } = makeFakeProjectAssetsClient();

    await saveProjectVideos(projectAssets, OWNER_A, "project-1", { s1: aiVideo("s1"), s2: aiVideo("s2") });

    expect(videoRows).toHaveLength(2);
    expect(videoRows[0]).toMatchObject({ project_id: "project-1", owner_id: OWNER_A, kind: "ai-video", scene_id: "s1", storage_path: "u/gen/videos/s1.mp4" });
    expect(videoRows[0].metadata).toMatchObject({ provider: "runway:gen4_turbo", model: "gen4_turbo", providerTaskId: "task-123", durationSeconds: 5, providerCost: 25 });
  });

  it("never persists a row for a video without a storagePath (not yet uploaded)", async () => {
    const { client: projectAssets, videoRows } = makeFakeProjectAssetsClient();
    await saveProjectVideos(projectAssets, OWNER_A, "project-1", { s1: aiVideo("s1", { storagePath: undefined }) });
    expect(videoRows).toHaveLength(0);
  });

  it("continues persisting remaining videos even when one insert fails", async () => {
    const rows: NewVideoAssetRow[] = [];
    const projectAssets: ProjectAssetsClient = {
      async insertVisualAsset() {
        return { ok: true };
      },
      async listAutoGeneratedVisuals() {
        return [];
      },
      async insertVideoAsset(row) {
        if (row.scene_id === "s1") return { ok: false, error: "db error" };
        rows.push(row);
        return { ok: true };
      },
      async listAiVideos() {
        return [];
      },
    };

    await saveProjectVideos(projectAssets, OWNER_A, "project-1", { s1: aiVideo("s1"), s2: aiVideo("s2") });

    expect(rows).toHaveLength(1);
    expect(rows[0].scene_id).toBe("s2");
  });
});

describe("loadProject videos", () => {
  it("re-signs and returns every persisted AI-generated video, keyed by scene id", async () => {
    const { client } = makeFakeProjectsClient();
    const { client: projectAssets } = makeFakeProjectAssetsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    await saveProjectVideos(projectAssets, OWNER_A, saved.projectId, {
      s1: {
        sceneId: "s1",
        url: "ignored-stale-url",
        source: "ai-generated",
        storagePath: "u/gen/videos/s1.mp4",
        provider: "runway:gen4_turbo",
        model: "gen4_turbo",
        providerTaskId: "task-1",
        durationSeconds: 5,
        motionPrompt: "steam rises and curls",
        providerCost: 25,
      },
    });

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId, projectAssets);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.videos.s1).toMatchObject({ sceneId: "s1", source: "ai-generated", storagePath: "u/gen/videos/s1.mp4", provider: "runway:gen4_turbo", providerCost: 25 });
    expect(result.videos.s1.url).toBe("https://storage.example/fresh-signed/u/gen/videos/s1.mp4"); // freshly re-signed, never the stale persisted one
  });

  it("returns an empty videos map when no ProjectAssetsClient is supplied (every existing caller keeps working unchanged)", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.videos).toEqual({});
  });

  it("(Requirement 10: graceful fallback) drops a video whose Storage object can no longer be re-signed, without failing the whole load", async () => {
    const { client } = makeFakeProjectsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const projectAssets: ProjectAssetsClient = {
      async insertVisualAsset() {
        return { ok: true };
      },
      async listAutoGeneratedVisuals() {
        return [];
      },
      async insertVideoAsset() {
        return { ok: true };
      },
      async listAiVideos() {
        return [{ scene_id: "s1", storage_path: "gone.mp4", provider: "runway:gen4_turbo", model: "gen4_turbo", provider_task_id: "task-1", duration_seconds: 5, motion_prompt: "x", provider_cost: 25 }];
      },
    };
    const brokenStorage: NarrationStorageClient = { from: () => ({ upload: async () => ({ error: null }), createSignedUrl: async () => ({ data: null, error: { message: "object not found" } }) }) };

    const result = await loadProject(client, brokenStorage, OWNER_A, saved.projectId, projectAssets);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.videos).toEqual({});
  });

  it("(Requirement 10: old-project compatibility) an old project with only visuals (no videos at all) still loads, with an empty videos map", async () => {
    const { client } = makeFakeProjectsClient();
    const { client: projectAssets } = makeFakeProjectAssetsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const saved = await saveGeneratedProject(client, ALWAYS_ALLOWED_ENTITLEMENT, OWNER_A, "brief", plan);
    if (!saved.ok) throw new Error("setup failed");

    const result = await loadProject(client, fakeStorage(), OWNER_A, saved.projectId, projectAssets);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.videos).toEqual({});
    expect(result.plan).toBeDefined();
  });
});
