import { describe, expect, it, vi } from "vitest";
import {
  startExport,
  checkExportProgress,
  findLatestCompletedExport,
  findActiveExport,
  type VideosClient,
  type RenderJobsClient,
  type VideoRow,
  type RenderJobRow,
  type LatestExportVideosClient,
  type LatestExportRenderJobsClient,
  type ActiveExportRenderJobsClient,
} from "@/lib/render/export-orchestration";
import { saveGeneratedProject, saveProjectNarration, type ProjectsClient, type ProjectRow, type ProjectAssetsClient, type PersistedVideoAssetRow } from "@/lib/actions/project-persistence";
import type { EntitlementClient } from "@/lib/supabase/usage";
import type { RenderClient, StartRenderInput, StartRenderResult, RenderProgressResult } from "@/lib/render/render-client";
import type { NarrationStorageClient } from "@/lib/audio/narration-storage";
import type { PlanNarrationResult } from "@/lib/audio/plan-narration";
import type { VideoPlan } from "@/lib/ai/video-plan-schema";

/**
 * Every dependency (Projects/Videos/RenderJobs DB clients, the render
 * backend, Storage, the output download) is an in-memory/hand-written fake
 * — no real Remotion Lambda, AWS, or Supabase call happens anywhere in this
 * file (Requirement: "no real paid/cloud rendering calls in automated
 * tests"). lib/actions/export-actions.ts wires the real implementations in
 * for production.
 */

function scene(id: string, narration: string | null): VideoPlan["scenes"][number] {
  return {
    id,
    startTime: 0,
    duration: 5,
    purpose: "hook",
    narration,
    onScreenText: "Hello",
    visualDirection: "product on table",
    motionDirection: "slow zoom",
    transition: "cut",
    assetNeeds: [],
    textPosition: "center",
    textAlign: "center",
    visual: null,
  };
}
const FILLER_SCENES = [scene("filler-1", null), scene("filler-2", null)];

function makePlan(overrides: Partial<VideoPlan> & { scenes: VideoPlan["scenes"] }): VideoPlan {
  return {
    language: "ar",
    videoTitle: "Acme Ad",
    business: "Acme Co",
    objective: "Sell burgers",
    targetAudience: "Young adults",
    platform: "reels",
    aspectRatio: "9:16",
    durationSeconds: 15,
    visualStyle: "fast",
    tone: "energetic",
    brandColors: null,
    palette: null,
    visualTheme: null,
    cta: "Order now",
    audio: null,
    ...overrides,
  };
}

const OWNER_A = "user-aaaa";
const OWNER_B = "user-bbbb";

function makeFakeProjectsClient() {
  const rows = new Map<string, ProjectRow & { owner_id: string }>();
  let nextId = 1;
  const client: ProjectsClient = {
    async insertProject(row) {
      const id = `project-${nextId++}`;
      rows.set(id, { id, prompt: row.prompt, scene_plan: row.scene_plan, narration: null, owner_id: row.owner_id });
      return { ok: true, id };
    },
    async updateProject(projectId, ownerId, patch) {
      const existing = rows.get(projectId);
      if (!existing || existing.owner_id !== ownerId) return { ok: false, error: "not found or not owned" };
      rows.set(projectId, { ...existing, ...patch });
      return { ok: true };
    },
    async selectProject(projectId, ownerId) {
      const existing = rows.get(projectId);
      if (!existing || existing.owner_id !== ownerId) return null;
      const { owner_id: _owner_id, ...row } = existing;
      return row;
    },
  };
  return { client, rows };
}

function fakeNarrationStorage(): NarrationStorageClient {
  return {
    from: () => ({
      upload: async () => ({ error: null }),
      createSignedUrl: async (path: string) => ({ data: { signedUrl: `https://storage.example/narration-signed/${path}` }, error: null }),
    }),
  };
}

/**
 * Dynamic AI Video Director export-pipeline regression coverage: a fake
 * ProjectAssetsClient whose `listAiVideos`/`listAutoGeneratedVisuals` return
 * exactly the rows a test configures — lets these tests prove a persisted
 * ai-video row actually survives the FULL startExport path (loadProject's
 * re-signing -> buildVideoPlanRenderData -> the real inputProps handed to
 * render.startRender), the one hop no earlier test (project-persistence.test.ts
 * tests loadProject alone; plan-to-scenes.test.ts tests buildVideoPlanRenderData
 * alone) ever exercised end to end.
 */
function makeFakeProjectAssetsClient(videoRows: PersistedVideoAssetRow[] = [], visualRows: { scene_id: string; storage_path: string }[] = []): ProjectAssetsClient {
  return {
    async insertVisualAsset() {
      return { ok: true };
    },
    async listAutoGeneratedVisuals(_projectId, _ownerId) {
      return visualRows.map((v) => ({ scene_id: v.scene_id, storage_path: v.storage_path, provider: "openai:gpt-image-1", prompt: "a prompt", estimated_usd: 0.07 }));
    },
    async insertVideoAsset() {
      return { ok: true };
    },
    async listAiVideos(_projectId, _ownerId) {
      return videoRows;
    },
  };
}

function makeAiVideoRow(sceneId: string, storagePath: string): PersistedVideoAssetRow {
  return {
    scene_id: sceneId,
    storage_path: storagePath,
    provider: "runway:gen4_turbo",
    model: "gen4_turbo",
    provider_task_id: "task-123",
    duration_seconds: 5,
    motion_prompt: "The mist drifts slowly across the frame.",
    provider_cost: 25,
  };
}

function makeFakeVideosClient() {
  const rows = new Map<string, VideoRow & { owner_id: string; project_id: string }>();
  let nextId = 1;
  const client: VideosClient = {
    async insertVideo(row) {
      const id = `video-${nextId++}`;
      rows.set(id, { id, status: row.status, storage_path: null, duration_seconds: row.duration_seconds, file_size_mb: null, owner_id: row.owner_id, project_id: row.project_id });
      return { ok: true, id };
    },
    async updateVideo(id, ownerId, patch) {
      const existing = rows.get(id);
      if (!existing || existing.owner_id !== ownerId) return { ok: false, error: "not found or not owned" };
      rows.set(id, { ...existing, ...patch });
      return { ok: true };
    },
    async selectVideo(id, ownerId) {
      const existing = rows.get(id);
      if (!existing || existing.owner_id !== ownerId) return null;
      return existing;
    },
  };
  return { client, rows };
}

function makeFakeRenderJobsClient() {
  const rows = new Map<string, RenderJobRow & { user_id: string }>();
  let nextId = 1;
  const client: RenderJobsClient = {
    async insertRenderJob(row) {
      const id = `job-${nextId++}`;
      rows.set(id, { id, project_id: row.project_id, video_id: row.video_id, status: row.status, progress: 0, server: row.server, error_message: null, user_id: row.user_id });
      return { ok: true, id };
    },
    async updateRenderJob(id, ownerId, patch) {
      const existing = rows.get(id);
      if (!existing || existing.user_id !== ownerId) return { ok: false, error: "not found or not owned" };
      rows.set(id, { ...existing, ...patch });
      return { ok: true };
    },
    async selectRenderJob(id, ownerId) {
      const existing = rows.get(id);
      if (!existing || existing.user_id !== ownerId) return { ok: true, job: null };
      return { ok: true, job: existing };
    },
    async hasActiveJobForProject(ownerId, projectId) {
      for (const row of rows.values()) {
        if (row.user_id === ownerId && row.project_id === projectId && (row.status === "queued" || row.status === "processing")) return true;
      }
      return false;
    },
  };
  return { client, rows };
}

function fakeRenderClient(overrides: Partial<RenderClient> = {}): RenderClient {
  return {
    startRender: overrides.startRender ?? (async (): Promise<StartRenderResult> => ({ ok: true, renderId: "render-abc", bucketName: "bucket-xyz" })),
    getRenderProgress: overrides.getRenderProgress ?? (async (): Promise<RenderProgressResult> => ({ ok: true, done: false, progress: 0.5 })),
  };
}

const FAKE_MP4_BYTES = Buffer.from("fake mp4 bytes");
function fakeDownloadFile(): (url: string) => Promise<{ buffer: Buffer; contentType: string }> {
  return vi.fn(async () => ({ buffer: FAKE_MP4_BYTES, contentType: "video/mp4" }));
}

/** Export tests aren't about entitlement — every project here is created as already-allowed. */
const ALWAYS_ALLOWED_ENTITLEMENT: EntitlementClient = {
  getStatus: async () => ({ trialAvailable: true, trialConsumed: false, activeSubscription: false, expiredSubscription: false, canGenerate: true }),
  consumeTrial: async () => ({ ok: true, status: "consumed" }),
};

async function setUpProjectWithNarration(projects: ProjectsClient, ownerId: string, plan: VideoPlan) {
  const saved = await saveGeneratedProject(projects, ALWAYS_ALLOWED_ENTITLEMENT, ownerId, "brief", plan);
  if (!saved.ok) throw new Error("setup failed");
  const narration: PlanNarrationResult = { narrationAudioUrls: {}, sceneAudio: {}, status: "none", cost: { characters: 0, estimatedUsd: null } };
  await saveProjectNarration(projects, ownerId, saved.projectId, plan, narration);
  return saved.projectId;
}

describe("startExport", () => {
  it("(first trial project can still export / failed export retry does not consume another trial) startExport never touches entitlement at all — a project that already exists was already entitled to be created, and exporting/retrying it spends no additional trial or subscription check", async () => {
    // No EntitlementClient is even a parameter of startExport/checkExportProgress
    // (see their input types above) — this test documents and locks in that
    // architectural guarantee: whether the owning user's trial is available,
    // consumed, or their subscription has since expired is irrelevant here.
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs, rows: jobRows } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const deps = { projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient(), ownerId: OWNER_A, projectId };

    const first = await startExport(deps);
    expect(first.ok).toBe(true);
    if (!first.ok) return;

    // Simulate that render failing, then retrying the export for the same project:
    await renderJobs.updateRenderJob(first.renderJobId, OWNER_A, { status: "failed", error_message: "render backend error" });
    const retry = await startExport(deps);

    expect(retry.ok).toBe(true);
    expect(jobRows.size).toBe(2); // the failed attempt + this retry — never blocked by any entitlement check
  });

  it("(own-project export allowed) creates a video + render_jobs row and starts the render", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos, rows: videoRows } = makeFakeVideosClient();
    const { client: renderJobs, rows: jobRows } = makeFakeRenderJobsClient();
    const plan = makePlan({ aspectRatio: "9:16", scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);

    const result = await startExport({
      projects,
      storage: fakeNarrationStorage(),
      videos,
      renderJobs,
      render: fakeRenderClient(),
      ownerId: OWNER_A,
      projectId,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const job = jobRows.get(result.renderJobId);
    expect(job?.status).toBe("queued");
    expect(job?.server).toBe("bucket-xyz:render-abc");
    expect(videoRows.get(job!.video_id!)?.status).toBe("processing");
    // 3 scenes x 5s each = 15s, known upfront from the plan's own render data — never left null waiting for the render to finish.
    expect(videoRows.get(job!.video_id!)?.duration_seconds).toBe(15);
  });

  it("(another user's project rejected) refuses to export a project owned by someone else", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);

    const result = await startExport({
      projects,
      storage: fakeNarrationStorage(),
      videos,
      renderJobs,
      render: fakeRenderClient(),
      ownerId: OWNER_B,
      projectId,
    });

    expect(result).toEqual({ ok: false, error: "Project not found.", code: "not_found" });
  });

  it("(no duplicate active job) refuses to start a second export while one is already queued/processing for the same project", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const deps = { projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient(), ownerId: OWNER_A, projectId };

    const first = await startExport(deps);
    expect(first.ok).toBe(true);

    const second = await startExport(deps);
    expect(second).toEqual({ ok: false, error: "An export is already in progress for this project.", code: "already_exporting" });
  });

  it("(correct output resolution) requests 1080x1920 for 9:16", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ aspectRatio: "9:16", scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId });

    expect(startRender).toHaveBeenCalledWith(expect.objectContaining({ inputProps: expect.objectContaining({ width: 1080, height: 1920 }) }));
  });

  it("(correct output resolution) requests 1920x1080 for 16:9", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ aspectRatio: "16:9", scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId });

    expect(startRender).toHaveBeenCalledWith(expect.objectContaining({ inputProps: expect.objectContaining({ width: 1920, height: 1080 }) }));
  });

  it("(correct output resolution) requests 1080x1080 for 1:1", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ aspectRatio: "1:1", scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId });

    expect(startRender).toHaveBeenCalledWith(expect.objectContaining({ inputProps: expect.objectContaining({ width: 1080, height: 1080 }) }));
  });

  it("(Dynamic AI Video Director export regression, Bug #1) a persisted ai-video row resolves to a signed videoUrl in the export render input props", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const projectAssets = makeFakeProjectAssetsClient([makeAiVideoRow("s1", "user/gen/videos/s1.mp4")]);
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId, projectAssets });

    const inputProps = startRender.mock.calls[0][0].inputProps as { scenes: Array<{ id: string; content: Record<string, string> }> };
    const s1 = inputProps.scenes.find((s: { id: string }) => s.id === "s1")!;
    expect(s1.content.videoUrl).toBe("https://storage.example/narration-signed/user/gen/videos/s1.mp4");
    expect(s1.content.videoDurationInFrames).toBe("150"); // 5s * 30fps
  });

  it("(Dynamic AI Video Director export regression) old projects without any ai-video rows still export correctly — content.videoUrl stays empty, no crash", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    const result = await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId });

    expect(result.ok).toBe(true);
    const inputProps = startRender.mock.calls[0][0].inputProps as { scenes: Array<{ id: string; content: Record<string, string> }> };
    const s1 = inputProps.scenes.find((s: { id: string }) => s.id === "s1")!;
    expect(s1.content.videoUrl).toBe("");
  });

  it("(Dynamic AI Video Director export regression) an ai-video AND an auto-generated visual can both resolve for the same scene — export input props carry both, so a video-unaware renderer would still show the still image rather than nothing", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const projectAssets = makeFakeProjectAssetsClient([makeAiVideoRow("s1", "user/gen/videos/s1.mp4")], [{ scene_id: "s1", storage_path: "user/gen/visuals/s1.png" }]);
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId, projectAssets });

    const inputProps = startRender.mock.calls[0][0].inputProps as { scenes: Array<{ id: string; content: Record<string, string> }> };
    const s1 = inputProps.scenes.find((s: { id: string }) => s.id === "s1")!;
    expect(s1.content.videoUrl).toBe("https://storage.example/narration-signed/user/gen/videos/s1.mp4");
    expect(s1.content.imageUrl).toBe("https://storage.example/narration-signed/user/gen/visuals/s1.png");
  });

  it("(Dynamic AI Video Director export regression) a video whose signed URL can't be re-issued gracefully falls back to the still image for export, never crashing the whole export", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const projectAssets = makeFakeProjectAssetsClient([makeAiVideoRow("s1", "user/gen/videos/s1.mp4")], [{ scene_id: "s1", storage_path: "user/gen/visuals/s1.png" }]);
    const flakyStorage: NarrationStorageClient = {
      from: () => ({
        upload: async () => ({ error: null }),
        createSignedUrl: async (path: string) =>
          path.includes("/videos/") ? { data: null, error: { message: "object not found" } } : { data: { signedUrl: `https://storage.example/narration-signed/${path}` }, error: null },
      }),
    };
    const startRender = vi.fn(async (_input: StartRenderInput): Promise<StartRenderResult> => ({ ok: true, renderId: "r", bucketName: "b" }));

    const result = await startExport({ projects, storage: flakyStorage, videos, renderJobs, render: fakeRenderClient({ startRender }), ownerId: OWNER_A, projectId, projectAssets });

    expect(result.ok).toBe(true);
    const inputProps = startRender.mock.calls[0][0].inputProps as { scenes: Array<{ id: string; content: Record<string, string> }> };
    const s1 = inputProps.scenes.find((s: { id: string }) => s.id === "s1")!;
    expect(s1.content.videoUrl).toBe("");
    expect(s1.content.imageUrl).toBe("https://storage.example/narration-signed/user/gen/visuals/s1.png");
  });

  it("(render uses persisted validated VideoPlan) fails cleanly for a project whose stored plan no longer validates", async () => {
    const { client: projects, rows } = makeFakeProjectsClient();
    const { client: videos } = makeFakeVideosClient();
    const { client: renderJobs } = makeFakeRenderJobsClient();
    rows.set("bad-project", { id: "bad-project", prompt: "x", scene_plan: { not: "a plan" }, narration: null, owner_id: OWNER_A });

    const result = await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render: fakeRenderClient(), ownerId: OWNER_A, projectId: "bad-project" });

    expect(result).toEqual({ ok: false, error: "Project not found.", code: "invalid" });
  });

  it("surfaces a render_unavailable error when the render backend isn't configured, without creating orphaned rows", async () => {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos, rows: videoRows } = makeFakeVideosClient();
    const { client: renderJobs, rows: jobRows } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const render = fakeRenderClient({ startRender: async () => ({ ok: false, error: "Remotion Lambda isn't configured yet." }) });

    const result = await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render, ownerId: OWNER_A, projectId });

    expect(result).toEqual({ ok: false, error: "Remotion Lambda isn't configured yet.", code: "render_unavailable" });
    expect(videoRows.size).toBe(0);
    expect(jobRows.size).toBe(0);
  });
});

describe("checkExportProgress", () => {
  async function setUpStartedExport(overrides: { startRender?: RenderClient["startRender"] } = {}) {
    const { client: projects } = makeFakeProjectsClient();
    const { client: videos, rows: videoRows } = makeFakeVideosClient();
    const { client: renderJobs, rows: jobRows } = makeFakeRenderJobsClient();
    const plan = makePlan({ scenes: [scene("s1", "one"), ...FILLER_SCENES] });
    const projectId = await setUpProjectWithNarration(projects, OWNER_A, plan);
    const render = fakeRenderClient(overrides);
    const started = await startExport({ projects, storage: fakeNarrationStorage(), videos, renderJobs, render, ownerId: OWNER_A, projectId });
    if (!started.ok) throw new Error("setup failed");
    return { videos, videoRows, renderJobs, jobRows, render, renderJobId: started.renderJobId };
  }

  it("(render job lifecycle) reports processing with the backend's progress while not done", async () => {
    const { renderJobs, jobRows, renderJobId } = await setUpStartedExport({
      startRender: async () => ({ ok: true, renderId: "r1", bucketName: "b1" }),
    });
    const render = fakeRenderClient({ getRenderProgress: async () => ({ ok: true, done: false, progress: 0.42 }) });

    const result = await checkExportProgress({
      renderJobs,
      videos: makeFakeVideosClient().client,
      render,
      storage: fakeNarrationStorage(),
      downloadFile: fakeDownloadFile(),
      ownerId: OWNER_A,
      renderJobId,
    });

    expect(result).toEqual({ ok: true, status: "processing", progress: 0.42 });
    expect(jobRows.get(renderJobId)?.status).toBe("processing");
    expect(jobRows.get(renderJobId)?.progress).toBe(0.42);
  });

  it("(render job lifecycle, durable output path, signed URL not persisted) completes: uploads to Storage, marks both rows succeeded, returns a signed URL", async () => {
    const setup = await setUpStartedExport();
    const render = fakeRenderClient({ getRenderProgress: async () => ({ ok: true, done: true, downloadUrl: "https://lambda-output.example/out.mp4" }) });
    const downloadFile = fakeDownloadFile();
    let uploadedPath: string | undefined;
    const storage: NarrationStorageClient = {
      from: (bucket: string) => ({
        upload: async (path: string) => {
          uploadedPath = path;
          expect(bucket).toBe("videos");
          return { error: null };
        },
        createSignedUrl: async (path: string) => ({ data: { signedUrl: `https://storage.example/video-signed/${path}` }, error: null }),
      }),
    };

    const result = await checkExportProgress({
      renderJobs: setup.renderJobs,
      videos: setup.videos,
      render,
      storage,
      downloadFile,
      ownerId: OWNER_A,
      renderJobId: setup.renderJobId,
    });

    expect(result.ok).toBe(true);
    if (result.ok && result.status === "succeeded") {
      expect(result.downloadUrl).toBe(`https://storage.example/video-signed/${uploadedPath}`);
    } else {
      throw new Error("expected succeeded");
    }
    expect(downloadFile).toHaveBeenCalledWith("https://lambda-output.example/out.mp4");
    expect(uploadedPath).toMatch(/^user-aaaa\/project-1\/job-1\.mp4$/);

    const job = setup.jobRows.get(setup.renderJobId);
    expect(job?.status).toBe("succeeded");
    expect(job?.progress).toBe(1);
    const video = setup.videoRows.get(job!.video_id!);
    expect(video?.status).toBe("ready");
    expect(video?.storage_path).toBe(uploadedPath);
    // The signed URL itself is never written to either row — only the durable path:
    expect(JSON.stringify(job)).not.toContain("storage.example");
    expect(JSON.stringify(video)).not.toContain("storage.example/video-signed");
  });

  it("(failed render updates job correctly) marks both rows failed with a useful error when the render backend reports one", async () => {
    const setup = await setUpStartedExport();
    const render = fakeRenderClient({ getRenderProgress: async () => ({ ok: false, error: "Chromium crashed on frame 42." }) });

    const result = await checkExportProgress({
      renderJobs: setup.renderJobs,
      videos: setup.videos,
      render,
      storage: fakeNarrationStorage(),
      downloadFile: fakeDownloadFile(),
      ownerId: OWNER_A,
      renderJobId: setup.renderJobId,
    });

    expect(result).toEqual({ ok: true, status: "failed", error: "Chromium crashed on frame 42." });
    const job = setup.jobRows.get(setup.renderJobId);
    expect(job?.status).toBe("failed");
    expect(job?.error_message).toBe("Chromium crashed on frame 42.");
    const video = setup.videoRows.get(job!.video_id!);
    expect(video?.status).toBe("failed");
  });

  it("(storage upload failure) marks both rows failed rather than completing without a real file", async () => {
    const setup = await setUpStartedExport();
    const render = fakeRenderClient({ getRenderProgress: async () => ({ ok: true, done: true, downloadUrl: "https://lambda-output.example/out.mp4" }) });
    const storage: NarrationStorageClient = {
      from: () => ({
        upload: async () => ({ error: { message: "bucket quota exceeded" } }),
        createSignedUrl: async () => ({ data: null, error: null }),
      }),
    };

    const result = await checkExportProgress({
      renderJobs: setup.renderJobs,
      videos: setup.videos,
      render,
      storage,
      downloadFile: fakeDownloadFile(),
      ownerId: OWNER_A,
      renderJobId: setup.renderJobId,
    });

    expect(result).toEqual({ ok: true, status: "failed", error: "bucket quota exceeded" });
    const job = setup.jobRows.get(setup.renderJobId);
    expect(job?.status).toBe("failed");
    expect(setup.videoRows.get(job!.video_id!)?.status).toBe("failed");
    // Never marked ready/succeeded when the file never actually landed in Storage:
    expect(job?.status).not.toBe("succeeded");
  });

  it("(ownership) another user cannot poll or affect someone else's render job", async () => {
    const setup = await setUpStartedExport();

    const result = await checkExportProgress({
      renderJobs: setup.renderJobs,
      videos: setup.videos,
      render: fakeRenderClient(),
      storage: fakeNarrationStorage(),
      downloadFile: fakeDownloadFile(),
      ownerId: OWNER_B,
      renderJobId: setup.renderJobId,
    });

    expect(result).toEqual({ ok: false, error: "Render job not found.", transient: false });
  });

  it("re-signs a fresh URL (never a cached one) when polled again after already succeeding", async () => {
    const setup = await setUpStartedExport();
    let signCount = 0;
    const storage: NarrationStorageClient = {
      from: () => ({
        upload: async () => ({ error: null }),
        createSignedUrl: async (path: string) => {
          signCount += 1;
          return { data: { signedUrl: `https://storage.example/video-signed/${path}?n=${signCount}` }, error: null };
        },
      }),
    };
    const render = fakeRenderClient({ getRenderProgress: async () => ({ ok: true, done: true, downloadUrl: "https://lambda-output.example/out.mp4" }) });

    const first = await checkExportProgress({ renderJobs: setup.renderJobs, videos: setup.videos, render, storage, downloadFile: fakeDownloadFile(), ownerId: OWNER_A, renderJobId: setup.renderJobId });
    const second = await checkExportProgress({ renderJobs: setup.renderJobs, videos: setup.videos, render, storage, downloadFile: fakeDownloadFile(), ownerId: OWNER_A, renderJobId: setup.renderJobId });

    expect(first.ok && first.status === "succeeded" && second.ok && second.status === "succeeded").toBe(true);
    if (first.ok && first.status === "succeeded" && second.ok && second.status === "succeeded") {
      expect(first.downloadUrl).not.toBe(second.downloadUrl);
    }
  });
});

/**
 * Pre-launch fix: ExportPanel.tsx checks this on mount/projectId-change so
 * reopening/reloading a project that was already exported shows "تحميل
 * الفيديو" immediately instead of risking a duplicate, paid re-export.
 * `findLatestCompletedExport`'s own input type has no RenderClient at all —
 * it is structurally impossible for this function to start a render;
 * these tests additionally prove it never even calls a write/insert method
 * on the fakes it's given, only the two read lookups plus a signed-URL
 * reissue.
 */
describe("findLatestCompletedExport", () => {
  function fakeLatestExportVideos(video: { id: string; storage_path: string | null } | null): LatestExportVideosClient {
    return { selectLatestReadyVideoForProject: vi.fn().mockResolvedValue(video) };
  }
  function fakeLatestExportRenderJobs(job: { id: string } | null): LatestExportRenderJobsClient {
    return { selectSucceededRenderJobForVideo: vi.fn().mockResolvedValue(job) };
  }

  it("(existing completed export rehydrates) returns a fresh signed download URL and the render job id when a ready video and its succeeded render job both exist", async () => {
    const videos = fakeLatestExportVideos({ id: "video-1", storage_path: "owner-1/project-1/job-1.mp4" });
    const renderJobs = fakeLatestExportRenderJobs({ id: "job-1" });

    const result = await findLatestCompletedExport({
      videos,
      renderJobs,
      storage: fakeNarrationStorage(),
      ownerId: OWNER_A,
      projectId: "project-1",
    });

    expect(result).toEqual({
      ok: true,
      found: true,
      downloadUrl: "https://storage.example/narration-signed/owner-1/project-1/job-1.mp4",
      renderJobId: "job-1",
    });
  });

  it("(no existing export keeps ExportPanel idle) returns found:false when the project has no ready video at all", async () => {
    const videos = fakeLatestExportVideos(null);
    const renderJobs = fakeLatestExportRenderJobs({ id: "job-1" });

    const result = await findLatestCompletedExport({ videos, renderJobs, storage: fakeNarrationStorage(), ownerId: OWNER_A, projectId: "project-1" });

    expect(result).toEqual({ ok: true, found: false });
    expect(renderJobs.selectSucceededRenderJobForVideo).not.toHaveBeenCalled();
  });

  it("(no existing export keeps ExportPanel idle) returns found:false when a ready video exists but has no storage_path yet", async () => {
    const videos = fakeLatestExportVideos({ id: "video-1", storage_path: null });
    const renderJobs = fakeLatestExportRenderJobs({ id: "job-1" });

    const result = await findLatestCompletedExport({ videos, renderJobs, storage: fakeNarrationStorage(), ownerId: OWNER_A, projectId: "project-1" });

    expect(result).toEqual({ ok: true, found: false });
  });

  it("(no existing export keeps ExportPanel idle) returns found:false when a ready video exists but no succeeded render job can be found for it", async () => {
    const videos = fakeLatestExportVideos({ id: "video-1", storage_path: "owner-1/project-1/job-1.mp4" });
    const renderJobs = fakeLatestExportRenderJobs(null);

    const result = await findLatestCompletedExport({ videos, renderJobs, storage: fakeNarrationStorage(), ownerId: OWNER_A, projectId: "project-1" });

    expect(result).toEqual({ ok: true, found: false });
  });

  it("(does not start a new render) calls only the two read lookups and a signed-URL reissue — never a write/insert on either fake client", async () => {
    const videos = fakeLatestExportVideos({ id: "video-1", storage_path: "owner-1/project-1/job-1.mp4" });
    const renderJobs = fakeLatestExportRenderJobs({ id: "job-1" });
    const upload = vi.fn();
    const storage = { from: () => ({ upload, createSignedUrl: async (path: string) => ({ data: { signedUrl: `https://storage.example/${path}` }, error: null }) }) };

    await findLatestCompletedExport({ videos, renderJobs, storage, ownerId: OWNER_A, projectId: "project-1" });

    expect(videos.selectLatestReadyVideoForProject).toHaveBeenCalledTimes(1);
    expect(renderJobs.selectSucceededRenderJobForVideo).toHaveBeenCalledTimes(1);
    expect(upload).not.toHaveBeenCalled();
  });

  it("(current-user scoping is preserved) scopes both the video and render job lookups to the exact ownerId and projectId passed in", async () => {
    const videos = fakeLatestExportVideos({ id: "video-1", storage_path: "path.mp4" });
    const renderJobs = fakeLatestExportRenderJobs({ id: "job-1" });

    await findLatestCompletedExport({ videos, renderJobs, storage: fakeNarrationStorage(), ownerId: "the-current-users-id", projectId: "the-project-id" });

    expect(videos.selectLatestReadyVideoForProject).toHaveBeenCalledWith("the-project-id", "the-current-users-id");
    expect(renderJobs.selectSucceededRenderJobForVideo).toHaveBeenCalledWith("video-1", "the-current-users-id");
  });

  it("surfaces a signing failure as ok:false rather than a fabricated URL", async () => {
    const videos = fakeLatestExportVideos({ id: "video-1", storage_path: "path.mp4" });
    const renderJobs = fakeLatestExportRenderJobs({ id: "job-1" });
    const storage = { from: () => ({ upload: vi.fn(), createSignedUrl: async () => ({ data: null, error: { message: "Storage is unavailable." } }) }) };

    const result = await findLatestCompletedExport({ videos, renderJobs, storage, ownerId: OWNER_A, projectId: "project-1" });

    expect(result).toEqual({ ok: false, error: "Storage is unavailable." });
  });
});

/**
 * Production incident fix: checkExportProgress must distinguish a transient
 * SELECT failure (`selectRenderJob` returning `{ok:false}`) from a
 * genuinely missing row (`{ok:true, job:null}`) — collapsing both into
 * `null` is exactly what made one flaky read during a long poll loop look
 * identical to "this render job never existed."
 */
describe("checkExportProgress (transient vs. genuine not-found)", () => {
  it("(Supabase query error is not interpreted as 'Render job not found') marks the result transient:true with the real query error, never the generic not-found message", async () => {
    const { client: videos } = makeFakeVideosClient();
    const renderJobs: RenderJobsClient = {
      insertRenderJob: vi.fn(),
      updateRenderJob: vi.fn(),
      hasActiveJobForProject: vi.fn().mockResolvedValue(false),
      async selectRenderJob() {
        return { ok: false, error: "Connection terminated unexpectedly." };
      },
    };

    const result = await checkExportProgress({
      renderJobs,
      videos,
      render: fakeRenderClient(),
      storage: fakeNarrationStorage(),
      downloadFile: fakeDownloadFile(),
      ownerId: OWNER_A,
      renderJobId: "job-1",
    });

    expect(result).toEqual({ ok: false, error: "Connection terminated unexpectedly.", transient: true });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).not.toBe("Render job not found.");
    }
  });

  it("a genuinely missing row (query succeeded, no row) is still reported not found, and NOT marked transient", async () => {
    const { client: videos } = makeFakeVideosClient();
    const renderJobs: RenderJobsClient = {
      insertRenderJob: vi.fn(),
      updateRenderJob: vi.fn(),
      hasActiveJobForProject: vi.fn().mockResolvedValue(false),
      async selectRenderJob() {
        return { ok: true, job: null };
      },
    };

    const result = await checkExportProgress({
      renderJobs,
      videos,
      render: fakeRenderClient(),
      storage: fakeNarrationStorage(),
      downloadFile: fakeDownloadFile(),
      ownerId: OWNER_A,
      renderJobId: "job-1",
    });

    expect(result).toEqual({ ok: false, error: "Render job not found.", transient: false });
  });
});

/**
 * The "resume an already-running export" recovery path — reopening a
 * project must be able to pick a genuinely active render back up without
 * ever calling startRender again. findActiveExport's own input type has no
 * RenderClient at all, matching findLatestCompletedExport's guarantee.
 */
describe("findActiveExport", () => {
  function fakeActiveRenderJobs(job: { id: string; status: "queued" | "processing"; progress: number } | null): ActiveExportRenderJobsClient {
    return { selectActiveRenderJobForProject: vi.fn().mockResolvedValue(job) };
  }

  it("(resume-existing-job path does not call startRender) returns the existing render job's id/status/progress for a still-processing job", async () => {
    const renderJobs = fakeActiveRenderJobs({ id: "job-42", status: "processing", progress: 0.46 });

    const result = await findActiveExport({ renderJobs, ownerId: OWNER_A, projectId: "project-1" });

    expect(result).toEqual({ found: true, renderJobId: "job-42", status: "processing", progress: 0.46 });
    // Structural guarantee: FindActiveExportInput has no `render`/RenderClient field at all —
    // there is no dependency this function could even call to start a render.
    expect(renderJobs.selectActiveRenderJobForProject).toHaveBeenCalledTimes(1);
  });

  it("returns found:false when the project has no queued/processing render job", async () => {
    const renderJobs = fakeActiveRenderJobs(null);
    const result = await findActiveExport({ renderJobs, ownerId: OWNER_A, projectId: "project-1" });
    expect(result).toEqual({ found: false });
  });

  it("(current-user scoping is preserved) scopes the lookup to the exact ownerId and projectId passed in", async () => {
    const renderJobs = fakeActiveRenderJobs({ id: "job-42", status: "queued", progress: 0 });
    await findActiveExport({ renderJobs, ownerId: "the-current-users-id", projectId: "the-project-id" });
    expect(renderJobs.selectActiveRenderJobForProject).toHaveBeenCalledWith("the-project-id", "the-current-users-id");
  });
});
