"use server";

import { requireUser } from "@/lib/supabase/auth-helpers";
import { createClient } from "@/lib/supabase/server";
import { realEntitlementClient } from "@/lib/supabase/usage";
import type { VideoPlan } from "@/lib/ai/video-plan-schema";
import type { PlanNarrationResult } from "@/lib/audio/plan-narration";
import {
  saveGeneratedProject,
  saveProjectNarration,
  saveProjectPlan,
  saveProjectVisuals,
  saveProjectVideos,
  loadProject,
  type ProjectsClient,
  type NewProjectRow,
  type ProjectRow,
  type SaveProjectResult,
  type SaveResult,
  type LoadProjectResult,
  type ProjectAssetsClient,
} from "@/lib/actions/project-persistence";
import type { ResolvedSceneVisual } from "@/lib/visuals/types";
import type { ResolvedSceneVideo } from "@/lib/video-generation/types";

export type { SaveProjectResult, SaveResult, LoadProjectResult } from "@/lib/actions/project-persistence";

/**
 * Minimal persistence layer for the real generation pipeline — reuses the
 * existing public.projects table (004_projects_video_jobs.sql) rather than
 * a new one; only supabase/migrations/016_projects_narration_audio.sql's
 * one new `narration` column was needed. Every one of these thin wrappers
 * adds auth + the real, authenticated (RLS-scoped, never service-role)
 * Supabase client and delegates to lib/actions/project-persistence.ts's
 * plain, unit-tested functions — same split as narration-actions.ts vs
 * plan-narration.ts. `projectId` is a plain parameter here, never a
 * security boundary by itself: every query is scoped to
 * `owner_id = user.id` both by the table's RLS policy AND explicitly in
 * the adapter below.
 */
/** Exported so lib/actions/export-actions.ts (which also needs to loadProject as part of starting an export) can reuse the exact same adapter instead of redeclaring it. */
export async function projectsClientForCurrentUser(): Promise<ProjectsClient> {
  const supabase = await createClient();

  return {
    async insertProject(row: NewProjectRow) {
      const { data, error } = await supabase.from("projects").insert(row).select("id").single();
      if (error || !data) return { ok: false, error: error?.message ?? "Failed to save the project." };
      return { ok: true, id: data.id };
    },
    async updateProject(projectId, ownerId, patch) {
      const { error } = await supabase.from("projects").update(patch).eq("id", projectId).eq("owner_id", ownerId);
      if (error) return { ok: false, error: error.message };
      return { ok: true };
    },
    async selectProject(projectId, ownerId): Promise<ProjectRow | null> {
      const { data } = await supabase
        .from("projects")
        .select("id, prompt, scene_plan, narration")
        .eq("id", projectId)
        .eq("owner_id", ownerId)
        .maybeSingle();
      return data;
    },
  };
}

/** Exported so lib/actions/visual-actions.ts and export-actions.ts can reuse the exact same adapter instead of redeclaring it — mirrors projectsClientForCurrentUser above. */
export async function projectAssetsClientForCurrentUser(): Promise<ProjectAssetsClient> {
  const supabase = await createClient();

  return {
    async insertVisualAsset(row) {
      const { error } = await supabase.from("project_assets").insert({
        project_id: row.project_id,
        owner_id: row.owner_id,
        kind: row.kind,
        scene_id: row.scene_id,
        storage_path: row.storage_path,
        mime_type: row.mime_type,
        metadata: row.metadata,
      });
      if (error) return { ok: false, error: error.message };
      return { ok: true };
    },
    async listAutoGeneratedVisuals(projectId, ownerId) {
      const { data } = await supabase
        .from("project_assets")
        .select("scene_id, storage_path, metadata")
        .eq("project_id", projectId)
        .eq("owner_id", ownerId)
        .eq("kind", "auto-generated");
      return (data ?? []).map((row) => {
        const metadata = (row.metadata ?? {}) as { prompt?: string; provider?: string; estimatedUsd?: number | null };
        return { scene_id: row.scene_id, storage_path: row.storage_path, provider: metadata.provider ?? null, prompt: metadata.prompt ?? null, estimated_usd: metadata.estimatedUsd ?? null };
      });
    },
    async insertVideoAsset(row) {
      const { error } = await supabase.from("project_assets").insert({
        project_id: row.project_id,
        owner_id: row.owner_id,
        kind: row.kind,
        scene_id: row.scene_id,
        storage_path: row.storage_path,
        mime_type: row.mime_type,
        metadata: row.metadata,
      });
      if (error) return { ok: false, error: error.message };
      return { ok: true };
    },
    async listAiVideos(projectId, ownerId) {
      const { data } = await supabase
        .from("project_assets")
        .select("scene_id, storage_path, metadata")
        .eq("project_id", projectId)
        .eq("owner_id", ownerId)
        .eq("kind", "ai-video");
      return (data ?? []).map((row) => {
        const metadata = (row.metadata ?? {}) as {
          provider?: string;
          model?: string;
          providerTaskId?: string;
          durationSeconds?: number;
          motionPrompt?: string;
          providerCost?: number | null;
        };
        return {
          scene_id: row.scene_id,
          storage_path: row.storage_path,
          provider: metadata.provider ?? null,
          model: metadata.model ?? null,
          provider_task_id: metadata.providerTaskId ?? null,
          duration_seconds: metadata.durationSeconds ?? null,
          motion_prompt: metadata.motionPrompt ?? null,
          provider_cost: metadata.providerCost ?? null,
        };
      });
    },
  };
}

export async function saveGeneratedProjectAction(prompt: string, plan: VideoPlan): Promise<SaveProjectResult> {
  const user = await requireUser();
  const projects = await projectsClientForCurrentUser();
  return saveGeneratedProject(projects, realEntitlementClient(), user.id, prompt, plan);
}

export async function saveProjectNarrationAction(projectId: string, plan: VideoPlan, narration: PlanNarrationResult): Promise<SaveResult> {
  const user = await requireUser();
  const projects = await projectsClientForCurrentUser();
  return saveProjectNarration(projects, user.id, projectId, plan, narration);
}

export async function saveProjectPlanAction(projectId: string, plan: VideoPlan): Promise<SaveResult> {
  const user = await requireUser();
  const projects = await projectsClientForCurrentUser();
  return saveProjectPlan(projects, user.id, projectId, plan);
}

/** Never throws — a Storage/DB hiccup here degrades to no durable visuals for this generation (the in-session preview keeps working; see lib/actions/visual-actions.ts's docstring), exactly like saveProjectNarrationAction's failure mode. */
export async function saveProjectVisualsAction(projectId: string, visuals: Record<string, ResolvedSceneVisual>): Promise<void> {
  const user = await requireUser();
  const projectAssets = await projectAssetsClientForCurrentUser();
  await saveProjectVisuals(projectAssets, user.id, projectId, visuals);
}

/** Never throws — a Storage/DB hiccup here degrades to no durable AI videos for this generation (the in-session preview keeps working), exactly like saveProjectVisualsAction's failure mode. */
export async function saveProjectVideosAction(projectId: string, videos: Record<string, ResolvedSceneVideo>): Promise<void> {
  const user = await requireUser();
  const projectAssets = await projectAssetsClientForCurrentUser();
  await saveProjectVideos(projectAssets, user.id, projectId, videos);
}

export async function loadProjectAction(projectId: string): Promise<LoadProjectResult> {
  const user = await requireUser();
  const supabase = await createClient();
  const projects = await projectsClientForCurrentUser();
  const projectAssets = await projectAssetsClientForCurrentUser();
  return loadProject(projects, supabase.storage, user.id, projectId, projectAssets);
}
